version: '3.4'

services:
  bookingap.api:
    image: ${DOCKER_REGISTRY-}bookingapapi
    build:
      context: .
      dockerfile: BookingAp.API/Dockerfile
    depends_on:
      - bookinap-db

  bookinap-db:
    image: postgres:latest
    container_name: Bookinap.Db
    restart: always
    environment:
      - POSTGRES_DB=Bookinapdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  bookinap.seq:
    image: datalust/seq:latest
    container_name: Bookinap-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5342:5342
      - 8081:80
  
  bookingap-idp:
    image: jboss/keycloak:latest
    container_name: BookingAp.Identity
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/BookingAp-realm-export.json
    volumes:
      - ./.containers/identity:/opt/jboss/keycloak/standalone/data
      - ./.files/BookingAp-realm-export.json:/tmp/BookingAp-realm-export.json
    ports:
      - 18080:8080

