version: '3.4'

services:
  bookingap.api:
    image: ${DOCKER_REGISTRY-}bookingapapi
    build:
      context: .
      dockerfile: BookingAp.API/Dockerfile
    depends_on:
      - bookinap-db

  bookinap-db:
    image: postgres:latest
    container_name: Bookinap.Db
    restart: always
    environment:
      - POSTGRES_DB=Bookinapdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  bookinap.seq:
    image: datalust/seq:latest
    container_name: Bookinap-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5342:5342
      - 8081:80

