version: '3.4'

services:
  bookingap.api:
    image: ${DOCKER_REGISTRY-}bookingapapi
    build:
      context: .
      dockerfile: BookingAp.API/Dockerfile
    depends_on:
      - bookinap-db

  bookinap-db:
    image: mysql:latest
    container_name: Bookinap.Db
    restart: always
    environment:
      MYSQL_DATABASE: 'Bookinapdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
       - 5432:5432   
    volumes:
       - ./.containers/database:/var/lib/mysql/data
